language: node_js
node_js: stable

# S: Build Lifecycle
before_script:
  - git config --global user.name "Honye"
  - git config --global user.email "hongye.jun@qq.com"
  - chmod +x ./deploy.sh  # 为shell文件添加可执行权限

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - ./deploy.sh
# E: Build LifeCycle

branches:
  only:
    - hexo-config
cache:
  directories:
    - node_modules
env:
 global:
   - GH_REF: github.com/Honye/Honye.github.io.git
   - CODING_REF: git.coding.net/Honye/Honye.git