language: node_js
node_js: stable

# S: Build Lifecycle
before_script:
  - git config --global user.name "Honye"
  - git config --global user.email "hongye.jun@qq.com"

install:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git --save
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git add .
  - git commit -m "Site updated"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo-config
cache:
  directories:
    - node_modules
env:
 global:
   - GH_REF: github.com/Hongye567/Hongye567.github.io