name: Hexo blog deployer

on:
  push:
    branches:
      - hexo-config

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - name: setup hexo env
        run: |
          npm install hexo-cli -g
          npm install

      - name: hexo generate
        run: |
          hexo clean
          hexo g

      - name: deploy
        env:
          GH_REF: github.com/Honye/Honye.github.io.git
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODING_REF: git.coding.net/Honye/Honye.git
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
        run: |
          chmod +x ./build.sh
          ./build.sh
